export default [
  {
    id: '1',
    name: 'Question1',
    type: 'type1',
    difficulty: 'Hard',
    detail: 'What’s your favorite way to spend a day off?',
  },
  {
    id: '2',
    name: 'Question2',
    type: 'type2',
    difficulty: 'Hard',
    detail: 'What type of music are you into?',
  },
  {
    id: '3',
    name: 'Question3',
    type: 'type3',
    difficulty: 'Hard',
    detail: 'What’s your favorite way to spend a day off?',
  },
  {
    id: '4',
    name: 'Question4',
    type: 'type4',
    difficulty: 'Hard',
    detail: 'What was the best vacation you ever took and why?',
  },
  {
    id: '5',
    name: 'Question1',
    type: 'type1',
    difficulty: 'Hard',
    detail: 'Where’s the next place on your travel bucket list and why?',
  },
  {
    id: '6',
    name: 'Question2',
    type: 'type2',
    difficulty: 'Hard',
    detail: 'What are your hobbies, and how did you get into them?',
  },
  {
    id: '7',
    name: 'Question3',
    type: 'type3',
    difficulty: 'Hard',
    detail: 'What’s your favorite way to spend a day off?',
  },
  {
    id: '12',
    name: 'Question4',
    type: 'type4',
    difficulty: 'Hard',
    detail: 'What was your favorite age growing up?',
  },
  {
    id: '8',
    name: 'Question1',
    type: 'type1',
    difficulty: 'Hard',
    detail: 'What was the last thing you read?',
  },
  {
    id: '9',
    name: 'Question2',
    type: 'type2',
    difficulty: 'Hard',
    detail: 'Would you say you’re more of an extrovert or an introvert?',
  },
  {
    id: '10',
    name: 'Question3',
    type: 'type3',
    difficulty: 'Hard',
    detail: 'What was the last TV show you binge-watched?',
  },
  {
    id: '11',
    name: 'Question4',
    type: 'type4',
    difficulty: 'Hard',
    detail: 'Are you into podcasts or do you only listen to music?',
  },
]
